// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvrwvcsnhejvdzzfnwfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2cnd2Y3NuaGVqdmR6emZud2Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDUyNjYsImV4cCI6MjA2MDgyMTI2Nn0.wJlxKvKHyVjr31tNIZ45lrEoOFZ7A1YnboHkcQA-NBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);